/**
 * PDF Layout Engine
 * Pure drawing primitives. No content logic here — only geometry and
 * positioning helpers. Every measurement comes from the design system.
 */

const { PAGE, SP, FONT, COLOR, hex } = require('./design');

// ── Text safety ───────────────────────────────────────────────────────────

/**
 * Truncate text so it never overflows a given pixel width.
 * Falls back to ellipsis rather than letting PDFKit guess.
 */
function safeText(doc, text, maxWidth, opts = {}) {
  if (!text) return '';
  const str  = String(text);
  const font = opts.font || FONT.REGULAR;
  const size = opts.size || FONT.size.md;

  doc.font(font).fontSize(size);
  if (doc.widthOfString(str) <= maxWidth) return str;

  let truncated = str;
  while (truncated.length > 1 && doc.widthOfString(truncated + '…') > maxWidth) {
    truncated = truncated.slice(0, -1);
  }
  return truncated + '…';
}

/**
 * Write text clamped to maxWidth — convenience wrapper around safeText.
 */
function clampedText(doc, text, x, y, maxWidth, opts = {}) {
  const safe  = safeText(doc, text, maxWidth, opts);
  const color = opts.color ? hex(opts.color) : hex(COLOR.textPri);
  doc.font(opts.font || FONT.REGULAR)
    .fontSize(opts.size || FONT.size.md)
    .fillColor(color)
    .text(safe, x, y, { lineBreak: false });
}

// ── Background fills ──────────────────────────────────────────────────────

function fillPage(doc, color = COLOR.bg) {
  doc.rect(0, 0, PAGE.width, PAGE.height).fill(hex(color));
}

function fillRect(doc, x, y, w, h, color) {
  doc.rect(x, y, w, h).fill(hex(color));
}

function fillRounded(doc, x, y, w, h, r, color) {
  doc.roundedRect(x, y, w, h, r).fill(hex(color));
}

function strokeRounded(doc, x, y, w, h, r, color, lw = 0.75) {
  doc.roundedRect(x, y, w, h, r).lineWidth(lw).strokeColor(hex(color)).stroke();
}

// ── Page chrome ───────────────────────────────────────────────────────────

/**
 * Draw the two-tone top accent bar (primary left / violet right).
 */
function accentBar(doc) {
  const barH = 4;
  fillRect(doc, 0,               0, PAGE.width / 2, barH, COLOR.primary);
  fillRect(doc, PAGE.width / 2,  0, PAGE.width / 2, barH, COLOR.violet);
}

/**
 * Draw the page footer rule + credit lines.
 */
function pageFooter(doc) {
  const fy = PAGE.height - 32;
  doc.moveTo(PAGE.margin, fy)
    .lineTo(PAGE.contentRight, fy)
    .lineWidth(0.5)
    .strokeColor(hex(COLOR.border))
    .stroke();

  doc.font(FONT.REGULAR)
    .fontSize(FONT.size.xs)
    .fillColor(hex(COLOR.textMuted))
    .text('Generated by ResumeIQ — AI-Powered ATS Resume Analyzer · For personal use only', PAGE.margin, fy + SP.sm);
}

// ── Horizontal divider ────────────────────────────────────────────────────

/**
 * Draw a full-width divider and return the new Y position.
 */
function divider(doc, y, gap = SP.md) {
  doc.moveTo(PAGE.margin, y)
    .lineTo(PAGE.contentRight, y)
    .lineWidth(0.5)
    .strokeColor(hex(COLOR.border))
    .stroke();
  return y + gap;
}

// ── Section heading ───────────────────────────────────────────────────────

/**
 * Draw an uppercase section heading with letter-spacing.
 * Returns Y below the heading.
 */
function sectionHeading(doc, text, y, gap = SP.lg) {
  doc.font(FONT.BOLD)
    .fontSize(FONT.size.xs)
    .fillColor(hex(COLOR.primary))
    .text(text.toUpperCase(), PAGE.margin, y, { characterSpacing: 1.4 });
  return y + gap;
}

// ── Progress bar ──────────────────────────────────────────────────────────

/**
 * Draw a labelled progress bar.
 *  label   — primary label (bold)
 *  value   — 0–100
 *  color   — hex fill color
 *  sub     — optional subtitle (muted, small)
 *  Returns Y below the bar.
 */
function progressBar(doc, { label, value, color, sub }, x, y, barW) {
  const fillW    = Math.round(Math.min(100, Math.max(0, value)) / 100 * barW);
  const trackH   = 4;
  const barTop   = y + (sub ? 26 : 18);

  // Label
  doc.font(FONT.BOLD).fontSize(FONT.size.md).fillColor(hex(COLOR.textPri)).text(label, x, y);

  // Subtitle
  if (sub) {
    const subStr = safeText(doc, sub, barW - 30, { font: FONT.REGULAR, size: FONT.size.xs });
    doc.font(FONT.REGULAR).fontSize(FONT.size.xs).fillColor(hex(COLOR.textMuted))
      .text(subStr, x, y + SP.sm + 2, { lineBreak: false });
  }

  // Percentage (right-aligned)
  doc.font(FONT.BOLD).fontSize(FONT.size.md).fillColor(hex(color))
    .text(`${value}%`, x + barW - 28, y, { lineBreak: false });

  // Track
  doc.roundedRect(x, barTop, barW, trackH, trackH / 2).fill(hex(COLOR.border));
  // Fill
  if (fillW > 0) {
    doc.roundedRect(x, barTop, fillW, trackH, trackH / 2).fill(hex(color));
  }

  return barTop + trackH + SP.sm;
}

// ── Arc / circle gauge ────────────────────────────────────────────────────

/**
 * Draw a circular progress arc centred at (cx, cy).
 * Uses many tiny line segments to approximate the arc.
 */
function arcGauge(doc, cx, cy, radius, score, color, lineWidth = 8) {
  // Track circle
  doc.circle(cx, cy, radius)
    .lineWidth(lineWidth)
    .strokeColor(hex(COLOR.border))
    .stroke();

  const total  = 2 * Math.PI;
  const filled = (Math.min(100, Math.max(0, score)) / 100) * total;
  const start  = -Math.PI / 2;
  const steps  = 120;
  const [r, g, b] = hex(color);

  doc.save().lineWidth(lineWidth).lineCap('round');
  for (let i = 0; i < steps; i++) {
    const t0 = start + (i       / steps) * filled;
    const t1 = start + ((i + 1) / steps) * filled;
    if (t1 > start + filled) break;
    doc
      .moveTo(cx + Math.cos(t0) * radius, cy + Math.sin(t0) * radius)
      .lineTo(cx + Math.cos(t1) * radius, cy + Math.sin(t1) * radius)
      .strokeColor([r, g, b])
      .stroke();
  }
  doc.restore();
}

// ── Keyword chip ──────────────────────────────────────────────────────────

/**
 * Draw a rounded keyword chip and return the next X position.
 */
function chip(doc, text, x, y, bgColor, fgColor) {
  const fontSize = FONT.size.xs;
  doc.font(FONT.BOLD).fontSize(fontSize);

  const safeLabel = safeText(doc, text, 100, { font: FONT.BOLD, size: fontSize });
  const tw = doc.widthOfString(safeLabel);
  const padX = 6, padY = 3;
  const bw = tw + padX * 2;
  const bh = fontSize + padY * 2;

  fillRounded(doc, x, y, bw, bh, 3, bgColor);
  doc.fillColor(hex(fgColor)).text(safeLabel, x + padX, y + padY, { lineBreak: false });
  return x + bw + SP.xs;
}

// ── Page overflow guard ───────────────────────────────────────────────────

/**
 * If current Y + requiredSpace overflows the page,
 * add a new page and reset to top margin.
 */
function ensureSpace(doc, y, requiredSpace) {
  if (y + requiredSpace > PAGE.contentBottom - PAGE.margin) {
    doc.addPage({ size: 'A4', margin: 0 });
    fillPage(doc);
    accentBar(doc);
    return PAGE.margin + SP.md;
  }
  return y;
}

module.exports = {
  safeText, clampedText,
  fillPage, fillRect, fillRounded, strokeRounded,
  accentBar, pageFooter, divider, sectionHeading,
  progressBar, arcGauge, chip, ensureSpace,
};
